### ISSUE TITLE
[Suggestion] Update "issue" template to title.

### ISSUE THREAD

**Issue by amaid** [Arlodotexe/strix-music#180]
Currently when you create an issue using bug template a title appears along with the issue.
"Describe the bug"

It'd we nice if its "Description" and not "Describe the bug".

![image](https://user-images.githubusercontent.com/15306909/176254594-f48f9206-e0b8-444b-9634-e61ee6efccdc.png)

**Comment by Arlodotexe** [comment]
I'd really like to revamp the "Bug report" issue template altogether.

I'm thinking something that's able to serve the majority of cases, while staying simple enough for everyone.

Maybe something like this (raw markdown or a form template equivalent):

```markdown
# The problem
<!--
Describe the problem.
Use screenshots or recordings if possible.
When did the issue first appear?
What version of the App or SDK?
Provide all information needed for us to reproduce the issue.
-->

# The solution
<!--
If unsure, leave this area empty
-->
```

**Comment by Arlodotexe** [comment]
> It'd we nice if its "Description" and not "Describe the bug".

Since this is for the "bug report" template, we'll likely leave this as is for now. There are other minor tweaks we could make to the template, but nothing that requires our immediate attention.
