### ISSUE TITLE
MediaInfo and MediaTransport control buttons are broken.

### ISSUE THREAD

**Issue by amaid** [Arlodotexe/strix-music#196]
### **UPDATE**
After through investigation turned out:
The media info and media transport is broken in the sandbox shell.

https://user-images.githubusercontent.com/15306909/179975881-225f5f32-4f66-4475-b293-59f2d6666d33.mp4

**Original Bug:**
Play/pause button to play/pause playback of sandbox shell isn't working. If you press it nothing happen.

### Affected area

- [ ] Strix Music SDK
- [X] Strix Music App

### Regression

https://user-images.githubusercontent.com/15306909/179052714-bc84eb31-ec71-45fa-8961-d1f7225ec3cf.mp4

### Steps to reproduce

```text
1. Switch to sandbox.
2. Play a song.
3. Try pressing play/pause button.
```

### Expected behavior

Tapping play button should play the song and tapping pause button should pause the song.

### Help us help you

Yes, I'd like to be assigned to work on this item.

**Comment by Arlodotexe** [comment]
Nice find, thank you @amaid!

**Comment by amaid** [comment]
Looks it was not just the playback, the mediaInfo and transport are both broken.
