### ISSUE TITLE
[Refactor] Rename the async methods in CollectionInit with "Async" suffix.

### ISSUE THREAD

**Issue by amaid** [Arlodotexe/strix-music#209]
All methods in the CollectionInit static class are asynchronous tasks. 
It would be nice to rename all of them with "Async" suffix for example:

```csharp 
public static async Task TrackCollection(ITrackCollectionViewModel trackCollection,
 CancellationToken cancellationToken)`
```

should be

```csharp 
public static async Task TrackCollectionAsync(ITrackCollectionViewModel trackCollection, 
CancellationToken cancellationToken)
```

![image](https://user-images.githubusercontent.com/15306909/181815443-f8175b20-acce-4a6f-b463-089e97d5cb6e.png)

**Comment by Arlodotexe** [comment]
Agreed and approved. Feel free to self-assign if you start working on this, otherwise I'll take this when I get a chance.
