### ISSUE TITLE
[Enhancment] Improve the loading animation

### ISSUE THREAD

**Issue by Avid29** [Arlodotexe/strix-music#214]
### Describe the problem

Currently the loop on the loading animation appears rushed. Adding .5 second to breath before looping should allow 

### Describe the proposed change

Change the last key frame of each animation in the loading storyboard to 2.5 seconds instead of 2.

### Help us help you

Yes, I'd like to be assigned to work on this item.

**Comment by Arlodotexe** [comment]
@Avid29 Since you've noted that you'd like to be assigned on this (and since you wrote the code originally) you've been given the ticket and can begin.
