### ISSUE TITLE
Crash when switching to Zune Desktop shell at runtime

### ISSUE THREAD

**Issue by Arlodotexe** [Arlodotexe/strix-music#231]
### Describe the bug

When you start the app on another shell and switch to Zune Desktop, the app crashes. The crash doesn't always happen immediately away after swapping, sometimes there's a 1 or 2 second delay.

### Affected area

- [ ] Strix Music SDK
- [X] Strix Music App

### Steps to reproduce

```text
1. Reset and set up the app. Set the shell to something other than Zune Desktop.
2. Restart the app
3. Switch to the Zune Desktop shell. Observe the crash.
```

### Visual repro steps

![image](https://user-images.githubusercontent.com/9384894/186956944-6556a0d8-73a3-4881-97cd-a7decfc20544.png)

### Expected behavior

No crash.

### Help us help you

No, I'm unable to contribute a solution.

**Comment by amaid** [comment]
@Arlodotexe I have been trying to produce this issue but no luck yet, tried uninstalling/resetting the app.
I'm able to switch b/w sandbox and zune shell without any issues.

**Comment by Arlodotexe** [comment]
That's so strange. I'm not able to reproduce it anymore either. Maybe it was a bug with Visual Studio or MSBuild or something. Closing for now.
