### ISSUE TITLE
[Refactor] Json Quip files 

### ISSUE THREAD

**Issue by Avid29** [Arlodotexe/strix-music#237]
### Describe the problem

I thought I was being clever using the resource files to swap the quips by language, but I wasn't. Then the situation got worse once we started adding event quips.

The system now depends on resource files and a ton of redundant information in the ``QuipLoader`` helper. It also makes it challenging to vary the number of quips by language.

### Describe the proposed change

Using Json files, the quips can be updated separately from the app, be added by third parties, and all of this can be managed simply by modifying the files. No changes to the code. 

### Additional info

I'm not sure how I would like to handle the built-in Quips. I'd think I'd like to have them stored as files in ``%StrixMusicAppData%\LocalState\Quips\`` along with third-party quip files, but I'm not sure how to best put them there on install. Alternatively, they could be loaded from embedded resources on each startup. This may be better for all I know.

### Help us help you

Yes, I'd like to be assigned to work on this item.

**Comment by Arlodotexe** [comment]
The Quip system has been removed for now, closing ticket.
