### ISSUE TITLE
Playback issues in Groove and Zune shell

### ISSUE THREAD

**Issue by Arlodotexe** [Arlodotexe/strix-music#248]
### Describe the bug

On `dev`, playback seems to only work on albums in the Zune shell. Anywhere else crashes the app.

### Affected area

- [ ] Strix Music SDK
- [X] Strix Music App

### Regression

0.0.2-app-alpha

### Steps to reproduce

```text
0) Swap to the `dev` branch. Uninstall, recompile and deploy the app.
1) Set up the app with a functional music source (local files tested here)
2) Swap to the Groove Music shell
3) Open an album
4) Try clicking the "Play" button on the header. It'll crash.
4a) Try double clicking a song. It'll crash
4b) Try playing a song from the "Tracks" collection in the library. It'll crash.
```

### Expected behavior

Playback should begin as expected.

### Help us help you

Yes, but only if others can assist.

**Comment by amaid** [comment]
After investigating this issue, it turned out the playback isn't working on the groove artist collection.
