### ISSUE TITLE
App stops playing when minimized

### ISSUE THREAD

**Issue by Arlodotexe** [Arlodotexe/strix-music#254]
### Describe the bug

When the Strix Music App is minimized, playback stops.

### Affected area

- [ ] Strix Music SDK
- [x] Strix Music App

### Steps to reproduce

```text
1. Open the app
2. Play something
3. Minimize the app. It'll pause.
```

### Expected behavior

Playback should continue normally

### Help us help you

Yes, but only if others can assist.

**Comment by yoshiask** [comment]
Here is one of the relevant docs for UWP:
https://learn.microsoft.com/en-us/windows/uwp/audio-video-camera/background-audio

**Comment by Arlodotexe** [comment]
It's possible that this is caused by the top-level refactor we did in #250. Check if [SystemMediaTransportControlsHandler](https://github.com/Arlodotexe/strix-music/blob/dev/src/Shared/MediaPlayback/SystemMediaTransportControlsHandler.cs) is being used.

**Comment by yoshiask** [comment]
VS doesn't find any references to `SystemMediaTransportControlsHandler` on the dev branch (apart from the class definition itself). Seems likely that this is the culprit.
