### ISSUE TITLE
[Feature] StrixDataRootPluginWrapper should expose the plugins provided in the constructor

### ISSUE THREAD

**Issue by Arlodotexe** [Arlodotexe/strix-music#280]
### Describe the problem

StrixDataRootPluginWrapper should expose the plugins provided in the constructor as a property. 

### Describe the proposed change

Add a `Plugins` property to `StrixDataRootPluginWrapper`, so that UI can access the plugins and create custom collections. 

### Additional info

Needed for #216

### Help us help you

None

**Comment by amaid** [comment]
This property is already part of the `StrixDataRootPluginWrapper` so closing this issue.
![image](https://github.com/Arlodotexe/strix-music/assets/15306909/9af09f75-3320-48fb-8a72-63b402b876f6)
