### ISSUE TITLE
Paid on patreon but it doesnt give access to alpah build

### ISSUE THREAD

**Issue by sojab0on** [Arlodotexe/strix-music#294]
Hi i have a subscrition to your patreon but i dont have an acess to the builds

i am seeking one for my lumia 950xl runs a fuly updated windows 10 mobile 1709

**Comment by sojab0on** [comment]
the lts builds on https://arlo.site/strixmusic/install/lts/ arent downloadble any more also so i cant get to a build to test

**Comment by Arlodotexe** [comment]
Strix Music v1 was discontinued.

v2 can be built from source or downloaded for free from the Microsoft Store [here](https://apps.microsoft.com/detail/9mwb3c32s2q7).
